create table artists
(
    artist_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    artist_name VARCHAR not NULL unique,
    birthday date not null, 
    birthplace VARCHAR not null ,
    is_alive boolean not null DEFAULT true 
)